### ISSUE TITLE
In React 18 you cannot add children to FadeIn. 

### ISSUE THREAD

**Issue by moodyVlad** [brunoluvizotto/react-slide-fade-in#1]
You need to change your typings.
From 
export declare const FadeIn: FC<Props>;
to 
export declare const FadeIn: FC<PropsWithChildren<Props>>;

**Comment by brunoluvizotto** [comment]
Thanks @moodyVlad. I'll take a look soon.

**Comment by brunoluvizotto** [comment]
Fixed in release v1.0.9
